"""
export_lgbm_v5_piper.py
-----------------------
Convert LGBM V5 model to Piper node JS format (same compact structure as V4/V6).
V5 has 312 features: bare underage tag names + adult__* adult counter-features.

Feature names are read from lgbm_evaluate_v5.js (the original text-format export),
since the model .txt file only stores generic Column_N names.
"""
import json, re, datetime
from pathlib import Path
import lightgbm as lgb

BASE_DIR = Path(__file__).resolve().parent.parent

def convert_tree(tree_structure):
    """Convert LightGBM recursive tree to compact arrays format.
    Returns: (splits, children, leaves)
    - splits: [[feature_idx, threshold], ...]  for each split node (in BFS order)
    - children: [[left, right], ...]           positive=split index, negative=-(leaf+1)
    - leaves: [leaf_value, ...]
    """
    splits = []
    children = []
    leaves = []
    # BFS traversal
    queue = [tree_structure]
    node_map = {}  # original node ptr -> index in splits array
    # We need two passes: first collect all nodes, then build children refs
    # Use recursive approach assigning indices during DFS

    split_nodes = []
    leaf_nodes = []

    def collect(node):
        if 'leaf_index' in node:
            # leaf node
            leaf_id = len(leaf_nodes)
            leaf_nodes.append(node['leaf_value'])
            return -(leaf_id + 1)  # negative = leaf
        else:
            # split node
            split_id = len(split_nodes)
            split_nodes.append(None)  # placeholder
            left_ref = collect(node['left_child'])
            right_ref = collect(node['right_child'])
            split_nodes[split_id] = (node['split_feature'], node['threshold'], left_ref, right_ref)
            return split_id  # positive = split index

    collect(tree_structure)

    splits_out = [[fi, thr] for fi, thr, l, r in split_nodes]
    children_out = [[l, r] for fi, thr, l, r in split_nodes]
    return splits_out, children_out, leaf_nodes


def main():
    model = lgb.Booster(model_file=str(BASE_DIR / 'data' / 'lgbm_underage_v5.txt'))
    dump = model.dump_model()

    # Feature names are NOT stored in the .txt model (numpy array was passed without names).
    # Read them from the original lgbm_evaluate_v5.js generated by train_lgbm_v5.py.
    orig_js = (BASE_DIR / 'data' / 'lgbm_evaluate_v5.js').read_text(encoding='utf-8')
    feats_match = re.search(r'const LGBM_FEATURES = (\[.*?\]);', orig_js)
    if not feats_match:
        raise RuntimeError("Could not find LGBM_FEATURES in lgbm_evaluate_v5.js")
    feature_names = json.loads(feats_match.group(1))

    print(f"Features: {len(feature_names)} (from lgbm_evaluate_v5.js)")
    print(f"Trees: {len(dump['tree_info'])}")
    print(f"Sample features: {feature_names[:5]}")

    trees = []
    for ti in dump['tree_info']:
        s, c, l = convert_tree(ti['tree_structure'])
        trees.append({"r": 0, "s": s, "c": c, "l": l})

    # Sample first tree for sanity check
    t0 = trees[0]
    print(f"Tree0: {len(t0['s'])} split nodes, {len(t0['l'])} leaves")

    # Build compact JS
    feats_js = json.dumps(feature_names, ensure_ascii=False, separators=(',', ':'))
    trees_js = json.dumps(trees, ensure_ascii=False, separators=(',', ':'))

    # Count new adult counter-features
    n_adult = sum(1 for f in feature_names if f.startswith('adult__'))
    n_underage = len(feature_names) - n_adult
    today = datetime.date.today().isoformat()

    # Build the Piper node JS (same format as V6)
    js = f"""// lgbm_evaluate — LGBM Underage Scorer
// Model v5: {len(feature_names)} features ({n_underage} underage + {n_adult} adult counter), 100 trees, 15 leaves, trained {today}
// Input: same `labels` flat object as evaluate_siglip receives
// Outputs: labels (array), details (json) — same pattern as evaluate_siglip

// ── Embedded LGBM model ({len(feature_names)} features, 100 trees) ──────────────
const LGBM_FEATURES = {feats_js};

const LGBM_TREES = {trees_js};

// ── Helpers (mirror of evaluate_siglip) ──────────────────────────────────────
function combineScores(labels, group) {{
  return 1 - group.reduce((prod, label) => prod * (1 - (labels[label] || 0)), 1);
}}

function lgbmPredict(vec) {{
  let score = 0.0;
  for (const t of LGBM_TREES) {{
    let node = t.r;
    while (node >= 0) {{
      const [fi, thr] = t.s[node];
      const [l, r] = t.c[node];
      node = vec[fi] <= thr ? l : r;
    }}
    score += t.l[-(node + 1)];
  }}
  return 1.0 / (1.0 + Math.exp(-score));
}}

// ── Build feature vector from flat adjusted labels ─────────────────────────
function buildVec(affected, minorRisk, adultConf, underageConf) {{
  const vec = new Array(LGBM_FEATURES.length).fill(0);
  const featIdx = {{}};
  LGBM_FEATURES.forEach((name, i) => {{ featIdx[name] = i; }});

  // V5 feature names:
  //   underage tags → bare name (strip "underage_" prefix, same as V4/V6)
  //   adult tags    → "adult__" + bare name (strip "adult_" prefix, add "adult__")
  for (const [key, val] of Object.entries(affected)) {{
    if (key.startsWith('underage_')) {{
      const fname = key.slice(9);  // strip "underage_"
      if (fname in featIdx) vec[featIdx[fname]] = val;
    }} else if (key.startsWith('adult_')) {{
      const fname = 'adult__' + key.slice(6);  // strip "adult_", add "adult__"
      if (fname in featIdx) vec[featIdx[fname]] = val;
    }}
  }}
  return vec;
}}

// ── Main ──────────────────────────────────────────────────────────────────────

export async function run({{ inputs }}) {{
  const {{ NextNode }} = DEFINITIONS;

  const LGBM_THRESHOLD = 0.80;

  const labels = inputs.labels || {{}};

  // ── Ratio rule (kept for disagree flag) ──────────────────────────────────
  const UNDERAGE_CONFIDENCE    = 0.72;
  const UNDERAGE_MIN_SCORE     = 0.035;
  const AUTO_TRIGGER_MINOR_RISK = 0.7;

  const affected = Object.fromEntries(
    Object.entries(labels).filter(([k]) =>
      k.startsWith('underage') || k.startsWith('adult')
    )
  );

  const MINOR_LABELS = Object.keys(affected).filter(k => k.startsWith('underage'));
  const ADULT_LABELS = Object.keys(affected).filter(k => k.startsWith('adult'));
  const minorRisk    = combineScores(affected, MINOR_LABELS);
  const adultConf    = combineScores(affected, ADULT_LABELS);
  const total        = minorRisk + adultConf;
  const underageConf = total > 0 ? minorRisk / total : 0;

  const ratioBlocked =
    (underageConf >= UNDERAGE_CONFIDENCE && minorRisk >= UNDERAGE_MIN_SCORE)
    || minorRisk >= AUTO_TRIGGER_MINOR_RISK;

  // ── LGBM ─────────────────────────────────────────────────────────────────
  const vec         = buildVec(affected, minorRisk, adultConf, underageConf);
  const lgbmScore   = lgbmPredict(vec);
  const lgbmBlocked = lgbmScore >= LGBM_THRESHOLD;

  const topFeats = LGBM_FEATURES
    .map((name, i) => ({{ name, val: vec[i] }}))
    .filter(f => f.val > 0.001)
    .sort((a, b) => b.val - a.val)
    .slice(0, 5)
    .map(f => `${{f.name}}=${{f.val.toFixed(3)}}`)
    .join(', ');

  const details = {{
    score:        Math.round(lgbmScore * 10000) / 10000,
    blocked:      lgbmBlocked,
    disagree:     ratioBlocked !== lgbmBlocked,
    top_features: topFeats,
  }};

  return NextNode.from({{
    outputs: {{
      labels:  lgbmBlocked ? ["underage"] : [],
      details: details,
    }}
  }});
}}
// v5
"""

    out = BASE_DIR / 'data' / 'lgbm_evaluate_v5_piper.js'
    out.write_text(js, encoding='utf-8')
    print(f"Written: {out}")
    print(f"Size: {out.stat().st_size:,} bytes, lines: {js.count(chr(10))}")

if __name__ == '__main__':
    main()
